language: node_js
node_js: '9.8.0'
install:
    - npm install -g travis-ci-cloudfront-invalidation
    - npm install
before_script:
    - npm run lint
script:
    - npm run build
deploy:
    provider: s3
    region: eu-central-1
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $DOMAIN
    local_dir: dist
    cache_control: 'max-age=5184000'
    on:
        branch: master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST